version: 2.1
executors:
  android_large:
    resource_class: large
    docker:
      - image: freeletics/android-sdk:1.4
  android_small:
    resource_class: small
    docker:
      - image: freeletics/android-sdk:1.4
  macos:
    parameters:
      resource_class:
        type: string
        default: medium
    macos:
      xcode: 11.7.0
    resource_class: << parameters.resource_class >>
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      HOMEBREW_NO_AUTO_UPDATE: 1

orbs:
  prepare-workflow: freeletics/prepare-mobile-workflow@1.7.0

commands:
  set_ruby_version:
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.7.0" > ~/.ruby-version

  add_ssh_key:
    steps:
      - run:
          name: "Adding Github ssh key."
          command: |
            mkdir ~/.ssh
            # Copied from checkout step
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts

  prepare_standalone_job:
    steps:
      - add_ssh_keys: # Add ssh key used for private pods
          fingerprints:
            - "2a:e6:ed:7c:3b:61:f5:05:9a:d1:82:5f:38:21:5d:94"
      - set_ruby_version



jobs:
  postman_test_data:
    docker:
      - image: sirech/newman-executor:13.6
    steps:
      - add_ssh_key
      - run:
          name: "Checkout Postman data creation repo"
          command: git clone git@github.com:freeletics/postman-data-generator.git
      - run:
          name: "Run collection"
          command: |
            cd postman-data-generator/appium_data
            npx newman run appium_new_user_create.postman_collection.json -d registration_data_iterations.csv -e staging.postman_environment.json --export-environment env.json
      - persist_to_workspace:
          root: postman-data-generator/appium_data
          paths:
            - env.json

  assemble_freeletics_android_release:
    executor: android_large
    steps:
      - add_ssh_key
      - run:
          no_output_timeout: 40m
          name: Assemble release
          command: |
            git clone git@github.com:freeletics/fl-application-android.git
            cd fl-application-android
            ./gradlew app:freeletics:assembleStagingApiRelease
      - persist_to_workspace:
          root: fl-application-android
          paths:
            - app/freeletics/build/outputs/apk/stagingApi/release/freeletics-stagingApi-release.apk
      - store_artifacts:
          path: fl-application-android/app/freeletics/build/outputs/apk/stagingApi/release/freeletics-stagingApi-release.apk
          destination: apks/freeletics-stagingApi-release.apk

  assemble_freeletics_ios_alpha:
    executor: macos
    steps:
      - prepare_standalone_job
      - run:
          no_output_timeout: 40m
          name: Assemble alpha
          command: |
            git clone git@github.com:freeletics/fl-certificates-ios.git
            git clone git@github.com:freeletics/fl-application-ios.git
            cd fl-application-ios
            bundle install
            bundle exec fastlane build_ipa
            ls
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - Freeletics.ipa
      - store_artifacts:
          path: fl-application-android/app/freeletics/build/outputs/apk/stagingApi/release/freeletics-stagingApi-release.apk
          destination: apks/freeletics-stagingApi-release.apk


  upload_apk_to_kobiton:
   executor: android_small
   steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload build to kobiton
          command: |
            export URL=$(curl -XPOST -H "Authorization: Basic ${KOBITON_AUTH}" -H "Content-type: application/json" -d '{
            "filename" :  "app-debug.apk"}' 'https://api.kobiton.com/v1/apps/uploadUrl' | jq -r .url)

            echo $URL

            curl  -T "app/freeletics/build/outputs/apk/stagingApi/release/freeletics-stagingApi-release.apk" \
             -H "Content-Type: application/octet-stream" \
             -H "x-amz-tagging: unsaved=true" \
             -X PUT $URL

            export RESP = $(curl -X POST https://api.kobiton.com/v1/apps \
              -H "Authorization: Basic ${KOBITON_AUTH}" \
              -H 'Content-Type: application/json'\
              -d '{
                  "filename" :  "master.apk",
                  "appPath" :  "app/freeletics/build/outputs/apk/stagingApi/release/freeletics-stagingApi-release.apk"
                  }')
            echo $RESP

            export ID=$(curl -X GET https://api.kobiton.com/v1/apps \
              -H "Authorization: Basic ${KOBITON_AUTH}" \
              -H 'Content-Type: application/json'\
            | jq -r .apps[-1].id)''
            echo $ID

  run_appium_tests_android:
    working_directory: /home/circleci/repo
    docker:
      - image: thenishant/appium
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: "Checkout Appium test repo"
          command: |
            apt-get -y update && apt-get -y install git
            git clone git@github.com:freeletics/Appium_e2e_tests.git
            cd Appium_e2e_tests
      - run:
          name: "Parse environment file containing the test data from postman and run tests"
          command: |
            apt-get -y update && apt-get -y install jq
            $( jq -r '.values[1].value as $k | "export EMAILS=\($k)"' env.json)
            echo "$EMAILS"
            cd Appium_e2e_tests && ./mvnw clean install -Dapp.os=ANDROID -Demails=${EMAILS} -Dis.kobiton=true
            ./mvnw clean test -DCoachAdaptationTest,CheckAudioRecommendationsTest -Dapp.os=ANDROID -Demails=${EMAILS} -Dis.kobiton=true -DbuildID=${ID}
      - store_artifacts:
          path: ./target/surefire-reports

  run_appium_tests_ios:
    working_directory: /home/circleci/repo
    docker:
      - image: thenishant/appium
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: "Adding Github ssh key."
          command: |
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run:
          name: "Checkout Appium test repo"
          command: |
            apt-get -y update && apt-get -y install git
            git clone git@github.com:freeletics/Appium_e2e_tests.git
            cd Appium_e2e_tests
            git checkout tests-adapted-kobiton

      - run:
          name: "Parse environment file containing the test data from postman and run tests"
          command: |
            apt-get -y update && apt-get -y install jq
            $( jq -r '.values[1].value as $k | "export EMAILS=\($k)"' env.json)
            echo "$EMAILS"
            cd Appium_e2e_tests && ./mvnw clean install -Dapp.os=IOS -Demails=${EMAILS} -Dis.kobiton=true
            ./mvnw clean test -Dsurefire.suiteXmlFiles=/src/test/resources/testng.xml -Dapp.os=IOS -Demails=${EMAILS} -Dis.kobiton=true

workflows:
  version: 2
  run_appium_tests_android:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - postman_test_data
      - run_appium_tests_android:
          requires:
            - postman_test_data


  run_appium_tests_ios:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - postman_test_data
      - run_appium_tests_ios:
          requires:
            - postman_test_data


  run_appium_tests_android_pull:
    jobs:
      - assemble_freeletics_android_release
      - upload_apk_to_kobiton:
          requires:
            - assemble_freeletics_android_release
      - assemble_freeletics_ios_alpha
      - run_appium_tests_android:
          requires:
            - upload_apk_to_kobiton
