version: 2.1
executors:
  android_large:
    resource_class: large
    docker:
      - image: freeletics/android-sdk:1.4
orbs:
  prepare-workflow: freeletics/prepare-mobile-workflow@1.7.0
commands:
  add_ssh_key:
    steps:
      - run:
          name: "Adding Github ssh key."
          # We're adding 10000 here to get the build number monotonically increasing
          # because we've changed the strategy how it is determined over time.
          command: |
            mkdir ~/.ssh
            # Copied from checkout step
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts

jobs:
  postman_test_data:
    docker:
      - image: sirech/newman-executor:13.6
    steps:
      - add_ssh_key
      - run:
          name: "Checkout Postman data creation repo"
          command: git clone git@github.com:freeletics/postman-data-generator.git
      - run:
          name: "Run collection"
          command: |
            cd postman-data-generator/appium_data
            npx newman run appium_new_user_create.postman_collection.json -d registration_data_iterations.csv -e staging.postman_environment.json --export-environment env.json
      - persist_to_workspace:
          root: postman-data-generator/appium_data
          paths:
            - env.json

  assemble_freeletics_app_testio_clean_release:
    executor: android_large
    steps:
      - add_ssh_key
      - run:
          name: Curl to generate presign url
          command: |
            curl -v -XPOST -H "Authorization: Basic ${KOBITON_AUTH}" -H "Content-type: application/json" -d '{
            "filename" :  "app-debug.apk"}' 'https://api.kobiton.com/v1/apps/uploadUrl'
            URL=“$(curl -XPOST -H 'Authorization: Basic ${KOBITON_AUTH}' -H "Content-type: application/json" -d '{
            "filename" :  "app-debug.apk"}' 'https://api.kobiton.com/v1/apps/uploadUrl'  | jq --raw-output .url)”





  run_appium_tests_android:
    working_directory: /home/circleci/repo
    docker:
      - image: thenishant/appium
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: "Adding Github ssh key."
          command: |
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run:
          name: "Checkout Appium test repo"
          command: |
            apt-get -y update && apt-get -y install git
            git clone git@github.com:freeletics/Appium_e2e_tests.git
            cd Appium_e2e_tests

      - run:
          name: "Parse environment file containing the test data from postman and run tests"
          command: |
            apt-get -y update && apt-get -y install jq
            $( jq -r '.values[1].value as $k | "export EMAILS=\($k)"' env.json)
            echo "$EMAILS"
            cd Appium_e2e_tests && ./mvnw clean install -Dapp.os=ANDROID -Demails=${EMAILS} -Dis.kobiton=true
            ./mvnw clean test -DCoachAdaptationTest,CheckAudioRecommendationsTest -Dapp.os=ANDROID -Demails=${EMAILS} -Dis.kobiton=true
      - store_artifacts:
          path: ./target/surefire-reports

  run_appium_tests_ios:
    working_directory: /home/circleci/repo
    docker:
      - image: thenishant/appium
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: "Adding Github ssh key."
          command: |
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run:
          name: "Checkout Appium test repo"
          command: |
            apt-get -y update && apt-get -y install git
            git clone git@github.com:freeletics/Appium_e2e_tests.git
            cd Appium_e2e_tests
            git checkout tests-adapted-kobiton

      - run:
          name: "Parse environment file containing the test data from postman and run tests"
          command: |
            apt-get -y update && apt-get -y install jq
            $( jq -r '.values[1].value as $k | "export EMAILS=\($k)"' env.json)
            echo "$EMAILS"
            cd Appium_e2e_tests && ./mvnw clean install -Dapp.os=IOS -Demails=${EMAILS} -Dis.kobiton=true
            ./mvnw clean test -Dsurefire.suiteXmlFiles=/src/test/resources/testng.xml -Dapp.os=IOS -Demails=${EMAILS} -Dis.kobiton=true

workflows:
  version: 2
  run_appium_tests_android:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - postman_test_data
      - run_appium_tests_android:
          requires:
            - postman_test_data


  run_appium_tests_ios:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - postman_test_data
      - run_appium_tests_ios:
          requires:
            - postman_test_data


  run_appium_tests_android_pull:
    jobs:
      - assemble_freeletics_app_testio_clean_release
      - run_appium_tests_android:
          requires:
            - assemble_freeletics_app_testio_clean_release
