version: 2
parameters:
  kobiton:
    type: boolean
    default: true

jobs:
  build:
    working_directory: /home/circleci/repo
    docker:
      - image: rgonalo/appium
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: "Adding Github ssh key."
          command: |
            mkdir ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - run:
          name: "Checkout Appium test repo"
          command: git clone git@github.com:freeletics/Appium_e2e_tests.git
      - run:
          name: run tests
          command: |
            cd Appium_e2e_tests
            appium
            ./mvnw clean test -Dsurefire.suiteXmlFiles=/src/test/resources/testng.xml -Dapp.os=ANDROID -Demails="" -Dis.kobiton=true
